### ISSUE TITLE
Can I trigger this with other import optimize feature of intellij

### ISSUE THREAD

**Issue by ScrapCodes** [aarondav/scala-imports-organizer#2]
I am using the same short cut i.e. Ctrl+ Shift + O for intellij's built in import optimize and also for this plugin (which is default.). Now only the built in action is run and not this one.

**Comment by aarondav** [comment]
Hm, there is a setting for "Remove Unused Imports" in this plugin's settings. This actually just runs the IntelliJ built in Scala import optimizer (without the prompt). Is this sufficient, or does it become a problem when you are trying to organize Java imports?

**Comment by ScrapCodes** [comment]
I see, Thanks ! Haven't tried with java yet.
