### ISSUE TITLE
Unicode arrows in import x.{y ⇒ z} do not work

### ISSUE THREAD

**Issue by stanch** [aarondav/scala-imports-organizer#5]
Here’s the import:

``` scala
import android.location.{Location ⇒ AndroidLocation}
```

And here’s the trace:

```
MatchError: Location ⇒ AndroidLocation (of class java.lang.String): Location ⇒ AndroidLocation (of class java.lang.String)
```

If I replace it with a `=>`, everything works.

**Comment by aarondav** [comment]
Added support for both reading unicode arrows and writing as unicode arrows through an option in the settings panel in 0.1.5...

(Do note that IntelliJ 13.1 supports import organization inherently, though, so hopefully you've been able to move on!)
