### ISSUE TITLE
Renamed imports followed by underscore

### ISSUE THREAD

**Issue by jctim** [aarondav/scala-imports-organizer#8]
_import org.mockito.Matchers.{eq => meq, _}_

turns into

_import org.mockito.Matchers.{_, eq => meq}_

but underscore should stay in the end

**Comment by aarondav** [comment]
Sorry about this. I have fixed it in 0.1.5 (https://github.com/aarondav/scala-imports-organizer/commit/ab88381c346ff86d9bfdc9f0a7ac37fab8bb57bb).

**Comment by jctim** [comment]
Thanks!
